### ISSUE TITLE
git fetch failed

### ISSUE THREAD

**Issue by naugtur** [taichi/actions-package-update#10]
I keep getting this:

```
[1590443623387] INFO  (1 on 926fcaaa51cd): Start process.
[1590443623389] DEBUG (1 on 926fcaaa51cd): START makeBranch
[1590443623389] DEBUG (1 on 926fcaaa51cd): getFile /github/workspace/package.json
[1590443623393] DEBUG (1 on 926fcaaa51cd): BEGIN git fetch --prune origin
Error: Command failed with exit code 128: git fetch --prune origin
    at makeError (/usr/local/share/.config/yarn/global/node_modules/execa/lib/error.js:56:11)
    at handlePromise (/usr/local/share/.config/yarn/global/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async h.makeBranch (/usr/local/share/.config/yarn/global/node_modules/actions-package-update/dist/index.js:12:1603)
    at async h.run (/usr/local/share/.config/yarn/global/node_modules/actions-package-update/dist/index.js:12:633)
    at async o (/usr/local/share/.config/yarn/global/node_modules/actions-package-update/dist/index.js:14:300) {
  command: 'git fetch --prune origin',
  exitCode: 128,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: "fatal: unable to access 'https://github.com/naugtur/handsfreeyoutube/': Problem with the SSL CA cert (path? access rights?)",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

Doesn't seem like something I misconfigured about the repo or access.

What am mI missing?

**Comment by naugtur** [comment]
ok, master works.

please tag a new version if you have the time :)
