### ISSUE TITLE
I want use email: github-actions[bot]@users.noreply.github.com

### ISSUE THREAD

**Issue by hirotoKirimaru** [taichi/actions-package-update#33]
I want use email: github-actions[bot]@users.noreply.github.com.

but , this line that format: email don't allow [].

https://github.com/taichi/actions-package-update/blob/5ab5dc4dcbf726ad322c95c83e7395990611921a/src/config.ts#L42

I remove that, but test failed.  because async test already broken. 
I hope you accept it.

**Comment by maboloshi** [comment]
The same robot email address `152410706+action-assistant[bot]@users.noreply.github.com` is also not accepted.

Error message:
```
Error: git.useremail: must be an email address: value was "152410706+action-assistant[bot]@users.noreply.github.com"
    at Object.validate (/usr/local/share/.config/yarn/global/node_modules/convict/src/main.js:679:17)
    at o (/usr/local/share/.config/yarn/global/node_modules/actions-package-update/dist/index.js:14:236)
    at parcelRequire.QCba../config (/usr/local/share/.config/yarn/global/node_modules/actions-package-update/dist/index.js:14:355)
    at f (/usr/local/share/.config/yarn/global/node_modules/actions-package-update/dist/index.js:1:468)
    at parcelRequire.C9JJ (/usr/local/share/.config/yarn/global/node_modules/actions-package-update/dist/index.js:1:771)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/actions-package-update/dist/index.js:1:1023)
    at Module._compile (node:internal/modules/cjs/loader:1460:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1544:10)
    at Module.load (node:internal/modules/cjs/loader:1275:32)
    at Module._load (node:internal/modules/cjs/loader:1091:12)
```
